name: tensorflow-fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0
  - numpy=1.24.4
  - pip:
      - tensorflow-gpu==2.10.1
      - fastapi>=0.100.0
      - uvicorn>=0.23.0
      - pydantic>=2.0.0
      - psutil>=5.9.0
      - py-cpuinfo>=9.0.0
      - python-multipart>=0.0.6
      - typing-extensions>=4.7.1
      - pyinstaller>=6.7.0
variables:
  PYTHONPATH: ${CONDA_PREFIX}/lib/python3.10/site-packages