// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { GetServerHealthError, GetServerHealthResponse, GetSystemInfoError, GetSystemInfoResponse, GetTensorflowInfoError, GetTensorflowInfoResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Health Check
 */
export const getServerHealth = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetServerHealthResponse, GetServerHealthError, ThrowOnError>({
        ...options,
        url: '/health'
    });
};

/**
 * Get System Info
 */
export const getSystemInfo = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSystemInfoResponse, GetSystemInfoError, ThrowOnError>({
        ...options,
        url: '/system/info'
    });
};

/**
 * Get Tensorflow Info
 */
export const getTensorflowInfo = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTensorflowInfoResponse, GetTensorflowInfoError, ThrowOnError>({
        ...options,
        url: '/tensorflow/info'
    });
};