// This file is auto-generated by @hey-api/openapi-ts

export type CPUCores = {
    /**
     * Number of physical CPU cores
     */
    physical: number;
    /**
     * Number of logical CPU cores
     */
    logical: number;
};

export type CPUFrequency = {
    /**
     * Current CPU frequency in MHz
     */
    current?: (number | null);
    /**
     * Minimum CPU frequency in MHz
     */
    min?: (number | null);
    /**
     * Maximum CPU frequency in MHz
     */
    max?: (number | null);
};

export type CPUInfo = {
    /**
     * CPU brand name
     */
    brand: string;
    cores: CPUCores;
    frequency: CPUFrequency;
};

export type GPUInfo = {
    /**
     * TensorFlow version
     */
    version: string;
    /**
     * Whether GPU is available
     */
    gpu_available: boolean;
    /**
     * List of available GPU devices
     */
    gpu_devices: Array<(string)>;
    /**
     * List of available CPU devices
     */
    cpu_devices: Array<(string)>;
    /**
     * Whether TensorFlow was built with CUDA
     */
    built_with_cuda: boolean;
    /**
     * Whether eager execution is enabled
     */
    eager_execution: boolean;
};

export type HealthCheck = {
    /**
     * Color of status of the API
     */
    color: string;
    /**
     * Health status of the API
     */
    status: string;
};

export type MemoryInfo = {
    /**
     * Total memory in bytes
     */
    total: number;
    /**
     * Available memory in bytes
     */
    available: number;
    /**
     * Used memory in bytes
     */
    used: number;
    /**
     * Memory usage percentage
     */
    percentage: number;
};

export type OSInfo = {
    /**
     * Operating system name
     */
    system: string;
    /**
     * OS release version
     */
    release: string;
    /**
     * OS version
     */
    version: string;
    /**
     * Machine architecture
     */
    machine: string;
};

export type SystemInfo = {
    os: OSInfo;
    cpu: CPUInfo;
    memory: MemoryInfo;
    /**
     * Python version
     */
    python_version: string;
};

export type GetServerHealthResponse = (HealthCheck);

export type GetServerHealthError = (unknown);

export type GetSystemInfoResponse = (SystemInfo);

export type GetSystemInfoError = (unknown);

export type GetTensorflowInfoResponse = (GPUInfo);

export type GetTensorflowInfoError = (unknown);